apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.service_type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "registry.selectorLabels" . | nindent 4 }}
