global:
  host: "loadtesting.xix.in"
  database:
    host: "10.9.0.7"
    user: "keycloak"
    port: "5432"
    vendor: "postgres"
  keycloak:
    database: "keycloak"
    admin:
      username: "admin"
    proxy_forwarding: true
  registry:
    database: "registry"
    search_provider: "dev.sunbirdrc.registry.service.ElasticSearchService"
    sso:
      realm: "sunbird-rc"
      admin_client_id: "admin-api"
      client_id: "registry-frontend"
    signature_enabled: true
    keycloak_user_set_password: false
    base_apis_enabled: false
    log_level: INFO
    enable_external_templates: true
    enable_async: false
    enable_authentication: true
    enable_webhook: false
    webhook_url: http://localhost:5001/api/v1/callback
    manager_type: DefinitionsManager
  minio:
    url: http://10.9.0.9:9000
    access_key: admin
    bucket_key: sunbird-rc
  elastic_search:
    url: 10.9.0.9:9200
    auth_enabled: false
    username: ""
  kafka:
    url:
  redis:
    host: 10.9.0.8
    port: 6379
  secrets:
    DB_PASSWORD: a2V5Y2xvYWs=
    ELASTIC_SEARCH_PASSWORD: ""
    KEYCLOAK_ADMIN_CLIENT_SECRET: YjJiMGNhYjEtMjQzZC00ZTZlLTkzZTctOTAxNWZmNjZkZjJi
    KEYCLOAK_ADMIN_PASSWORD: YWRtaW4xMjM=
    KEYCLOAK_DEFAULT_USER_PASSWORD: YWRtaW5AMTIz
    MINIO_SECRET_KEY: Kgo=
